cd /d %~dp0
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\AsyncStreamReaderExtensions.cs" "..\..\..\..\MagicOnion\AsyncStreamReaderExtensions.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\ClientStreamingResult.cs" "..\..\..\..\MagicOnion\ClientStreamingResult.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\DuplexStreamingResult.cs" "..\..\..\..\MagicOnion\DuplexStreamingResult.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\DynamicArgumentTuple.cs" "..\..\..\..\MagicOnion\DynamicArgumentTuple.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\GenerateDefineDebugAttribute.cs" "..\..\..\..\MagicOnion\GenerateDefineDebugAttribute.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\IgnoreAttribute.cs" "..\..\..\..\MagicOnion\IgnoreAttribute.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\IService.cs" "..\..\..\..\MagicOnion\IService.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\IStreamingHub.cs" "..\..\..\..\MagicOnion\IStreamingHub.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\MagicOnionMarshallers.cs" "..\..\..\..\MagicOnion\MagicOnionMarshallers.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\MetadataExtensions.cs" "..\..\..\..\MagicOnion\MetadataExtensions.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\ReturnStatusException.cs" "..\..\..\..\MagicOnion\ReturnStatusException.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\ServerStreamingResult.cs" "..\..\..\..\MagicOnion\ServerStreamingResult.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\UnaryResult.cs" "..\..\..\..\MagicOnion\UnaryResult.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\Server\Hubs\BroadcasterHelper.cs" "..\..\..\..\..\..\MagicOnion\Server\Hubs\BroadcasterHelper.cs"
mklink ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\Server\Hubs\MethodIdAttribute.cs" "..\..\..\..\..\..\MagicOnion\Server\Hubs\MethodIdAttribute.cs"
mklink /D ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\Utils" "..\..\..\..\MagicOnion\Utils"
mklink /D ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\CompilerServices" "..\..\..\..\MagicOnion\CompilerServices"
mklink /D ".\src\MagicOnion.Client.Unity\Assets\Scripts\MagicOnion\Client" "..\..\..\..\MagicOnion\Client"