using MessagePack;

namespace AotSample.Shared;

/// <summary>
/// MessagePack resolver generated by Source Generator for AOT support.
/// This resolver provides formatters for all [MessagePackObject] types in this assembly.
/// </summary>
[GeneratedMessagePackResolver]
public partial class AotSampleResolver;
