// <auto-generated />
#pragma warning disable

namespace MyApplication1
{
    partial class MagicOnionInitializer
    {
        static partial class MagicOnionGeneratedClient
        {
            [global::MagicOnion.Ignore]
            public class MyApplication1_MyServiceClient : global::MagicOnion.Client.MagicOnionClientBase<global::MyApplication1.IMyService>, global::MyApplication1.IMyService
            {
                class ClientCore
                {
                    public global::MagicOnion.Client.Internal.RawMethodInvoker<global::MessagePack.Nil, global::MessagePack.Nil> MethodA;
                    public ClientCore(global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider)
                    {
                        this.MethodA = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_ValueType_ValueType<global::MessagePack.Nil, global::MessagePack.Nil>(global::Grpc.Core.MethodType.Unary, "IMyService", "MethodA", serializerProvider);
                    }
                 }

                readonly ClientCore core;

                public MyApplication1_MyServiceClient(global::MagicOnion.Client.MagicOnionClientOptions options, global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider) : base(options)
                {
                    this.core = new ClientCore(serializerProvider);
                }

                private MyApplication1_MyServiceClient(global::MagicOnion.Client.MagicOnionClientOptions options, ClientCore core) : base(options)
                {
                    this.core = core;
                }

                protected override global::MagicOnion.Client.MagicOnionClientBase<global::MyApplication1.IMyService> Clone(global::MagicOnion.Client.MagicOnionClientOptions options)
                    => new MyApplication1_MyServiceClient(options, core);

                public global::MagicOnion.UnaryResult MethodA()
                    => this.core.MethodA.InvokeUnaryNonGeneric(this, "IMyService/MethodA", global::MessagePack.Nil.Default);
            }
        }
    }
}
