// <auto-generated />
#pragma warning disable 618
#pragma warning disable 612
#pragma warning disable 414
#pragma warning disable 219
#pragma warning disable 168

// NOTE: Disable warnings for nullable reference types.
// `#nullable disable` causes compile error on old C# compilers (-7.3)
#pragma warning disable 8603 // Possible null reference return.
#pragma warning disable 8618 // Non-nullable variable must contain a non-null value when exiting constructor. Consider declaring it as nullable.
#pragma warning disable 8625 // Cannot convert null literal to non-nullable reference type.

namespace TempProject
{
    using global::System;
    using global::Grpc.Core;
    using global::MagicOnion;
    using global::MagicOnion.Client;
    using global::MessagePack;
    
    [global::MagicOnion.Ignore]
    public class MyServiceClient : global::MagicOnion.Client.MagicOnionClientBase<global::TempProject.IMyService>, global::TempProject.IMyService
    {
        class ClientCore
        {
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::System.String, global::System.String> ClientStreamingAsync;
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::MessagePack.Nil, global::System.String> ServerStreamingAsync;
            public global::MagicOnion.Client.Internal.RawMethodInvoker<global::System.String, global::System.String> DuplexStreamingAsync;
            public ClientCore(global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider)
            {
                this.ClientStreamingAsync = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_RefType_RefType<global::System.String, global::System.String>(global::Grpc.Core.MethodType.ClientStreaming, "IMyService", "ClientStreamingAsync", serializerProvider);
                this.ServerStreamingAsync = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_ValueType_RefType<global::MessagePack.Nil, global::System.String>(global::Grpc.Core.MethodType.ServerStreaming, "IMyService", "ServerStreamingAsync", serializerProvider);
                this.DuplexStreamingAsync = global::MagicOnion.Client.Internal.RawMethodInvoker.Create_RefType_RefType<global::System.String, global::System.String>(global::Grpc.Core.MethodType.DuplexStreaming, "IMyService", "DuplexStreamingAsync", serializerProvider);
            }
        }
        
        readonly ClientCore core;
        
        public MyServiceClient(global::MagicOnion.Client.MagicOnionClientOptions options, global::MagicOnion.Serialization.IMagicOnionSerializerProvider serializerProvider) : base(options)
        {
            this.core = new ClientCore(serializerProvider);
        }
        
        private MyServiceClient(MagicOnionClientOptions options, ClientCore core) : base(options)
        {
            this.core = core;
        }
        
        protected override global::MagicOnion.Client.MagicOnionClientBase<IMyService> Clone(global::MagicOnion.Client.MagicOnionClientOptions options)
            => new MyServiceClient(options, core);
        
        public global::System.Threading.Tasks.Task<global::MagicOnion.ClientStreamingResult<global::System.String, global::System.String>> ClientStreamingAsync()
            => this.core.ClientStreamingAsync.InvokeClientStreaming(this, "IMyService/ClientStreamingAsync");
        public global::System.Threading.Tasks.Task<global::MagicOnion.ServerStreamingResult<global::System.String>> ServerStreamingAsync()
            => this.core.ServerStreamingAsync.InvokeServerStreaming(this, "IMyService/ServerStreamingAsync", global::MessagePack.Nil.Default);
        public global::System.Threading.Tasks.Task<global::MagicOnion.DuplexStreamingResult<global::System.String, global::System.String>> DuplexStreamingAsync()
            => this.core.DuplexStreamingAsync.InvokeDuplexStreaming(this, "IMyService/DuplexStreamingAsync");
    }
}


