// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 15.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace MagicOnion.Generator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MagicOnion.CodeAnalysis;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public partial class CodeTemplate : CodeTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("#pragma warning disable 618\r\n#pragma warning disable 612\r\n#pragma warning disable" +
                    " 414\r\n#pragma warning disable 219\r\n#pragma warning disable 168\r\n\r\n");
            
            #line 13 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace != null ? ("namespace " + Namespace + " {") : ""));
            
            #line default
            #line hidden
            this.Write("\r\n    using MagicOnion;\r\n    using MagicOnion.Client;\r\n    using Grpc.Core;\r\n    " +
                    "using MessagePack;\r\n");
            
            #line 18 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 foreach(var interfaceDef in Interfaces) { 
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 20 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(interfaceDef.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#if DEBUG\r\n");
            
            #line 22 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 23 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 var clientName = interfaceDef.Name + "Client"; 
            
            #line default
            #line hidden
            this.Write("    public class ");
            
            #line 24 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(clientName));
            
            #line default
            #line hidden
            this.Write(" : MagicOnionClientBase<");
            
            #line 24 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.FullName));
            
            #line default
            #line hidden
            this.Write(">, ");
            
            #line 24 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.FullName));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n");
            
            #line 26 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 foreach(var item in interfaceDef.Methods) { 
            
            #line default
            #line hidden
            
            #line 27 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#if DEBUG\r\n");
            
            #line 29 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        static readonly Method<byte[], byte[]> ");
            
            #line 30 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("Method;\r\n");
            
            #line 31 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#endif\r\n");
            
            #line 33 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 34 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n        static ");
            
            #line 36 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(clientName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n");
            
            #line 38 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 foreach(var item in interfaceDef.Methods) { 
            
            #line default
            #line hidden
            
            #line 39 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#if DEBUG\r\n");
            
            #line 41 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 42 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("Method = new Method<byte[], byte[]>(MethodType.");
            
            #line 42 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.MethodType.ToString()));
            
            #line default
            #line hidden
            this.Write(", \"");
            
            #line 42 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.Name));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 42 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("\", MagicOnionMarshallers.ThroughMarshaller, MagicOnionMarshallers.ThroughMarshall" +
                    "er);\r\n");
            
            #line 43 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#endif\r\n");
            
            #line 45 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 46 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        ");
            
            #line 49 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(clientName));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n        }\r\n\r\n        public ");
            
            #line 53 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(clientName));
            
            #line default
            #line hidden
            this.Write("(CallInvoker callInvoker, IFormatterResolver resolver)\r\n            : base(callIn" +
                    "voker, resolver)\r\n        {\r\n        }\r\n\r\n        protected override MagicOnionC" +
                    "lientBase<");
            
            #line 58 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.Name));
            
            #line default
            #line hidden
            this.Write("> Clone()\r\n        {\r\n            var clone = new ");
            
            #line 60 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(clientName));
            
            #line default
            #line hidden
            this.Write("();\r\n            clone.host = this.host;\r\n            clone.option = this.option;" +
                    "\r\n            clone.callInvoker = this.callInvoker;\r\n            clone.resolver " +
                    "= this.resolver;\r\n            return clone;\r\n        }\r\n\r\n        public new ");
            
            #line 68 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.Name));
            
            #line default
            #line hidden
            this.Write(" WithHeaders(Metadata headers)\r\n        {\r\n            return base.WithHeaders(he" +
                    "aders);\r\n        }\r\n\r\n        public new ");
            
            #line 73 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.Name));
            
            #line default
            #line hidden
            this.Write(" WithCancellationToken(System.Threading.CancellationToken cancellationToken)\r\n   " +
                    "     {\r\n            return base.WithCancellationToken(cancellationToken);\r\n     " +
                    "   }\r\n\r\n        public new ");
            
            #line 78 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.Name));
            
            #line default
            #line hidden
            this.Write(" WithDeadline(System.DateTime deadline)\r\n        {\r\n            return base.WithD" +
                    "eadline(deadline);\r\n        }\r\n\r\n        public new ");
            
            #line 83 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.Name));
            
            #line default
            #line hidden
            this.Write(" WithHost(string host)\r\n        {\r\n            return base.WithHost(host);\r\n     " +
                    "   }\r\n\r\n        public new ");
            
            #line 88 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(interfaceDef.Name));
            
            #line default
            #line hidden
            this.Write(" WithOptions(CallOptions option)\r\n        {\r\n            return base.WithOptions(" +
                    "option);\r\n        }\r\n   \r\n");
            
            #line 93 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 foreach(var item in interfaceDef.Methods) { 
            
            #line default
            #line hidden
            
            #line 94 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#if DEBUG\r\n");
            
            #line 96 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 97 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ToString()));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n");
            
            #line 99 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.MethodType == MethodType.Unary) { 
            
            #line default
            #line hidden
            this.Write("            var __request = ");
            
            #line 100 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.RequestObject()));
            
            #line default
            #line hidden
            this.Write(";\r\n            var __callResult = callInvoker.AsyncUnaryCall(");
            
            #line 101 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("Method, base.host, base.option, __request);\r\n");
            
            #line 102 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.IsResponseTypeTaskOfT) { 
            
            #line default
            #line hidden
            this.Write("            return System.Threading.Tasks.Task.FromResult(new UnaryResult<");
            
            #line 103 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ResponseType));
            
            #line default
            #line hidden
            this.Write(">(__callResult, base.resolver));\r\n");
            
            #line 104 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("            return new UnaryResult<");
            
            #line 105 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ResponseType));
            
            #line default
            #line hidden
            this.Write(">(__callResult, base.resolver);\r\n");
            
            #line 106 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 107 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } else if(item.MethodType ==MethodType.ServerStreaming) { 
            
            #line default
            #line hidden
            this.Write("            var __request = ");
            
            #line 108 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.RequestObject()));
            
            #line default
            #line hidden
            this.Write(";\r\n            var __callResult = callInvoker.AsyncServerStreamingCall(");
            
            #line 109 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("Method, base.host, base.option, __request);\r\n            return System.Threading." +
                    "Tasks.Task.FromResult(new ServerStreamingResult<");
            
            #line 110 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ResponseType));
            
            #line default
            #line hidden
            this.Write(">(__callResult, base.resolver));\r\n");
            
            #line 111 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } else if(item.MethodType ==MethodType.ClientStreaming) { 
            
            #line default
            #line hidden
            this.Write("            var __callResult = callInvoker.AsyncClientStreamingCall<byte[], byte[" +
                    "]>(");
            
            #line 112 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("Method, base.host, base.option);\r\n            return System.Threading.Tasks.Task." +
                    "FromResult(new ClientStreamingResult<");
            
            #line 113 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.RequestType));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 113 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ResponseType));
            
            #line default
            #line hidden
            this.Write(">(__callResult, base.resolver));\r\n");
            
            #line 114 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } else if(item.MethodType ==MethodType.DuplexStreaming) { 
            
            #line default
            #line hidden
            this.Write("            var __callResult = callInvoker.AsyncDuplexStreamingCall<byte[], byte[" +
                    "]>(");
            
            #line 115 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.Name));
            
            #line default
            #line hidden
            this.Write("Method, base.host, base.option);\r\n            return System.Threading.Tasks.Task." +
                    "FromResult(new DuplexStreamingResult<");
            
            #line 116 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.RequestType));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 116 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(item.ResponseType));
            
            #line default
            #line hidden
            this.Write(">(__callResult, base.resolver));\r\n");
            
            #line 117 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("        }\r\n");
            
            #line 119 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(item.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#endif\r\n");
            
            #line 121 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 122 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("    }\r\n");
            
            #line 124 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 if(interfaceDef.IsIfDebug) { 
            
            #line default
            #line hidden
            this.Write("#endif \r\n");
            
            #line 126 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 127 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 128 "C:\GitHubRepositories\MagicOnion\src\MagicOnion.UniversalCodeGenerator\Generator\CodeTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace != null ? "}" : ""));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n#pragma warning restore 168\r\n#pragma warning restore 219\r\n#pragma warning res" +
                    "tore 414\r\n#pragma warning restore 618\r\n#pragma warning restore 612");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "15.0.0.0")]
    public class CodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
