// <auto-generated />
#pragma warning disable

namespace MyNamespace
{
    using global::System;
    using global::MessagePack;

    partial class MagicOnionInitializer
    {
        /// <summary>
        /// Gets the generated MessagePack formatter resolver.
        /// </summary>
        public static global::MessagePack.IFormatterResolver Resolver => MessagePackGeneratedResolver.Instance;
        class MessagePackGeneratedResolver : global::MessagePack.IFormatterResolver
        {
            public static readonly global::MessagePack.IFormatterResolver Instance = new MessagePackGeneratedResolver();

            MessagePackGeneratedResolver() {}

            public global::MessagePack.Formatters.IMessagePackFormatter<T> GetFormatter<T>()
                => FormatterCache<T>.formatter;

            static class FormatterCache<T>
            {
                public static readonly global::MessagePack.Formatters.IMessagePackFormatter<T> formatter;

                static FormatterCache()
                {
                    var f = MessagePackGeneratedGetFormatterHelper.GetFormatter(typeof(T));
                    if (f != null)
                    {
                        formatter = (global::MessagePack.Formatters.IMessagePackFormatter<T>)f;
                    }
                }
            }
        }
        static class MessagePackGeneratedGetFormatterHelper
        {
            static readonly global::System.Collections.Generic.Dictionary<global::System.Type, int> lookup;

            static MessagePackGeneratedGetFormatterHelper()
            {
                lookup = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(4)
                {
                    {typeof(global::System.IO.FileMode), 0},
                    {typeof(global::System.Net.Http.ClientCertificateOption), 1},
                    {typeof(global::System.Threading.ApartmentState), 2},
                    {typeof(global::System.Threading.Tasks.TaskCreationOptions), 3},
                };
            }
            internal static object GetFormatter(global::System.Type t)
            {
                int key;
                if (!lookup.TryGetValue(t, out key))
                {
                    return null;
                }
            
                switch (key)
                {
                    case 0: return new MessagePackEnumFormatters.FileModeFormatter();
                    case 1: return new MessagePackEnumFormatters.ClientCertificateOptionFormatter();
                    case 2: return new MessagePackEnumFormatters.ApartmentStateFormatter();
                    case 3: return new MessagePackEnumFormatters.TaskCreationOptionsFormatter();
                    default: return null;
                }
            }
        }
    }
}
