// <auto-generated />
#pragma warning disable CS0618 // 'member' is obsolete: 'text'
#pragma warning disable CS0612 // 'member' is obsolete

namespace MagicOnion.Formatters
{
    using global::System;
    using global::MessagePack;

    public sealed class FileModeFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::System.IO.FileMode>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::System.IO.FileMode value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((Int32)value);
        }
        
        public global::System.IO.FileMode Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::System.IO.FileMode)reader.ReadInt32();
        }
    }
}
