using System.Text;
using MagicOnion.Server.SourceGenerator.CodeAnalysis;

namespace MagicOnion.Server.SourceGenerator.CodeGen;

public static class StaticMethodProviderGenerator
{
    public static string Generate(
        string namespaceName,
        string className,
        IReadOnlyList<ServiceImplementationInfo> services)
    {
        var sb = new StringBuilder();

        // Header
        sb.AppendLine("""
            // <auto-generated />
            #pragma warning disable CS0618 // Obsolete
            #pragma warning disable CS0612 // Obsolete
            #pragma warning disable CS8019 // Unnecessary using
            #nullable enable

            using System;
            using System.Collections.Generic;
            using System.Threading.Tasks;
            using MagicOnion;
            using MagicOnion.Server;
            using MagicOnion.Server.Binder;
            using MagicOnion.Server.Hubs;
            using MagicOnion.Internal;
            using MessagePack;

            """);

        // Namespace
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        // Main class implementing IMagicOnionGrpcMethodProvider
        GenerateMainClass(sb, className, services);

        // Generate method classes for each service
        foreach (var service in services)
        {
            if (service.IsStreamingHub)
            {
                GenerateStreamingHubMethodsClass(sb, service);
            }
            else
            {
                GenerateServiceMethodsClass(sb, service);
            }
        }

        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void GenerateMainClass(StringBuilder sb, string className, IReadOnlyList<ServiceImplementationInfo> services)
    {
        var indent = "    ";

        sb.AppendLine($"{indent}partial class {className} : global::MagicOnion.Server.Binder.IMagicOnionGrpcMethodProvider");
        sb.AppendLine($"{indent}{{");

        // MapAllSupportedServiceTypes
        sb.AppendLine($"{indent}    public void MapAllSupportedServiceTypes(global::MagicOnion.Server.Binder.MagicOnionGrpcServiceMappingContext context)");
        sb.AppendLine($"{indent}    {{");
        foreach (var service in services)
        {
            sb.AppendLine($"{indent}        context.Map<{service.ImplementationType.FullName}>();");
        }
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // GetGrpcMethods<TService>
        sb.AppendLine($"{indent}    public global::System.Collections.Generic.IReadOnlyList<global::MagicOnion.Server.Binder.IMagicOnionGrpcMethod> GetGrpcMethods<TService>() where TService : class");
        sb.AppendLine($"{indent}    {{");

        foreach (var service in services)
        {
            sb.AppendLine($"{indent}        if (typeof(TService) == typeof({service.ImplementationType.FullName}))");
            if (service.IsStreamingHub)
            {
                sb.AppendLine($"{indent}            return __{GetSafeTypeName(service.ImplementationType)}_HubConnectMethods.Methods;");
            }
            else
            {
                sb.AppendLine($"{indent}            return __{GetSafeTypeName(service.ImplementationType)}_ServiceMethods.Methods;");
            }
        }

        sb.AppendLine($"{indent}        return global::System.Array.Empty<global::MagicOnion.Server.Binder.IMagicOnionGrpcMethod>();");
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine();

        // GetStreamingHubMethods<TService>
        sb.AppendLine($"{indent}    public global::System.Collections.Generic.IReadOnlyList<global::MagicOnion.Server.Binder.IMagicOnionStreamingHubMethod> GetStreamingHubMethods<TService>() where TService : class");
        sb.AppendLine($"{indent}    {{");

        foreach (var service in services.Where(s => s.IsStreamingHub))
        {
            sb.AppendLine($"{indent}        if (typeof(TService) == typeof({service.ImplementationType.FullName}))");
            sb.AppendLine($"{indent}            return __{GetSafeTypeName(service.ImplementationType)}_HubMethods.Methods;");
        }

        sb.AppendLine($"{indent}        return global::System.Array.Empty<global::MagicOnion.Server.Binder.IMagicOnionStreamingHubMethod>();");
        sb.AppendLine($"{indent}    }}");

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void GenerateServiceMethodsClass(StringBuilder sb, ServiceImplementationInfo service)
    {
        var indent = "    ";
        var safeTypeName = GetSafeTypeName(service.ImplementationType);
        var implTypeName = service.ImplementationType.FullName;
        var serviceName = service.ServiceInterfaceType.Name;

        sb.AppendLine($"{indent}file static class __{safeTypeName}_ServiceMethods");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    public static readonly global::System.Collections.Generic.IReadOnlyList<global::MagicOnion.Server.Binder.IMagicOnionGrpcMethod> Methods = new global::MagicOnion.Server.Binder.IMagicOnionGrpcMethod[]");
        sb.AppendLine($"{indent}    {{");

        foreach (var method in service.Methods)
        {
            GenerateServiceMethodInstance(sb, service, method, indent + "        ");
        }

        sb.AppendLine($"{indent}    }};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void GenerateServiceMethodInstance(StringBuilder sb, ServiceImplementationInfo service, ServiceMethodInfo method, string indent)
    {
        var implTypeName = service.ImplementationType.FullName;
        var serviceName = service.ServiceInterfaceType.Name;
        var requestType = method.RequestType.FullName;
        var responseType = method.ResponseType.FullName;

        // Determine raw types (Box<T> for value types)
        var rawRequestType = method.RequestType.IsValueType
            ? $"global::MagicOnion.Internal.Box<{requestType}>"
            : requestType;
        var rawResponseType = method.ResponseType.IsValueType
            ? $"global::MagicOnion.Internal.Box<{responseType}>"
            : responseType;

        // Generate invoker lambda
        var invokerLambda = GenerateServiceInvokerLambda(service, method);

        switch (method.MethodType)
        {
            case MethodType.Unary when method.ResponseType == MagicOnionTypeInfo.KnownTypes.MessagePack_Nil:
                // MagicOnionUnaryMethod<TService, TRequest, TRawRequest>
                sb.AppendLine($"{indent}new global::MagicOnion.Server.Binder.MagicOnionUnaryMethod<{implTypeName}, {requestType}, {rawRequestType}>(\"{serviceName}\", \"{method.MethodName}\", {invokerLambda}),");
                break;

            case MethodType.Unary:
                // MagicOnionUnaryMethod<TService, TRequest, TResponse, TRawRequest, TRawResponse>
                sb.AppendLine($"{indent}new global::MagicOnion.Server.Binder.MagicOnionUnaryMethod<{implTypeName}, {requestType}, {responseType}, {rawRequestType}, {rawResponseType}>(\"{serviceName}\", \"{method.MethodName}\", {invokerLambda}),");
                break;

            case MethodType.ClientStreaming:
                // MagicOnionClientStreamingMethod<TService, TRequest, TResponse, TRawRequest, TRawResponse>
                sb.AppendLine($"{indent}new global::MagicOnion.Server.Binder.MagicOnionClientStreamingMethod<{implTypeName}, {requestType}, {responseType}, {rawRequestType}, {rawResponseType}>(\"{serviceName}\", \"{method.MethodName}\", {invokerLambda}),");
                break;

            case MethodType.ServerStreaming:
                // MagicOnionServerStreamingMethod<TService, TRequest, TResponse, TRawRequest, TRawResponse>
                sb.AppendLine($"{indent}new global::MagicOnion.Server.Binder.MagicOnionServerStreamingMethod<{implTypeName}, {requestType}, {responseType}, {rawRequestType}, {rawResponseType}>(\"{serviceName}\", \"{method.MethodName}\", {invokerLambda}),");
                break;

            case MethodType.DuplexStreaming:
                // MagicOnionDuplexStreamingMethod<TService, TRequest, TResponse, TRawRequest, TRawResponse>
                sb.AppendLine($"{indent}new global::MagicOnion.Server.Binder.MagicOnionDuplexStreamingMethod<{implTypeName}, {requestType}, {responseType}, {rawRequestType}, {rawResponseType}>(\"{serviceName}\", \"{method.MethodName}\", {invokerLambda}),");
                break;
        }
    }

    static string GenerateServiceInvokerLambda(ServiceImplementationInfo service, ServiceMethodInfo method)
    {
        var implTypeName = service.ImplementationType.FullName;

        if (method.MethodType == MethodType.ClientStreaming || method.MethodType == MethodType.DuplexStreaming)
        {
            // (instance, context) => instance.MethodName()
            return $"static ({implTypeName} instance, global::MagicOnion.Server.ServiceContext context) => instance.{method.MethodName}()";
        }

        // (instance, context, request) => instance.MethodName(request) or instance.MethodName(request.Item1, request.Item2, ...)
        var requestType = method.RequestType.FullName;

        if (method.Parameters.Count == 0)
        {
            return $"static ({implTypeName} instance, global::MagicOnion.Server.ServiceContext context, {requestType} request) => instance.{method.MethodName}()";
        }
        else if (method.Parameters.Count == 1)
        {
            return $"static ({implTypeName} instance, global::MagicOnion.Server.ServiceContext context, {requestType} request) => instance.{method.MethodName}(request)";
        }
        else
        {
            var args = string.Join(", ", method.Parameters.Select((p, i) => $"request.Item{i + 1}"));
            return $"static ({implTypeName} instance, global::MagicOnion.Server.ServiceContext context, {requestType} request) => instance.{method.MethodName}({args})";
        }
    }

    static void GenerateStreamingHubMethodsClass(StringBuilder sb, ServiceImplementationInfo service)
    {
        var indent = "    ";
        var safeTypeName = GetSafeTypeName(service.ImplementationType);
        var implTypeName = service.ImplementationType.FullName;
        var serviceName = service.ServiceInterfaceType.Name;

        // Hub connect method (for GetGrpcMethods)
        sb.AppendLine($"{indent}file static class __{safeTypeName}_HubConnectMethods");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    public static readonly global::System.Collections.Generic.IReadOnlyList<global::MagicOnion.Server.Binder.IMagicOnionGrpcMethod> Methods = new global::MagicOnion.Server.Binder.IMagicOnionGrpcMethod[]");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        new global::MagicOnion.Server.Binder.MagicOnionStreamingHubConnectMethod<{implTypeName}>(\"{serviceName}\"),");
        sb.AppendLine($"{indent}    }};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();

        // Hub methods (for GetStreamingHubMethods)
        sb.AppendLine($"{indent}file static class __{safeTypeName}_HubMethods");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    public static readonly global::System.Collections.Generic.IReadOnlyList<global::MagicOnion.Server.Binder.IMagicOnionStreamingHubMethod> Methods = new global::MagicOnion.Server.Binder.IMagicOnionStreamingHubMethod[]");
        sb.AppendLine($"{indent}    {{");

        foreach (var method in service.HubMethods)
        {
            GenerateStreamingHubMethodInstance(sb, service, method, indent + "        ");
        }

        sb.AppendLine($"{indent}    }};");
        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void GenerateStreamingHubMethodInstance(StringBuilder sb, ServiceImplementationInfo service, StreamingHubMethodInfo method, string indent)
    {
        var implTypeName = service.ImplementationType.FullName;
        var serviceName = service.ServiceInterfaceType.Name;
        var requestType = method.RequestType.FullName;
        var responseType = method.ResponseType.FullName;

        // Generate invoker lambda
        var invokerLambda = GenerateHubInvokerLambda(service, method);

        if (method.ResponseType == MagicOnionTypeInfo.KnownTypes.MessagePack_Nil)
        {
            // MagicOnionStreamingHubMethod<TService, TRequest>
            sb.AppendLine($"{indent}new global::MagicOnion.Server.Binder.MagicOnionStreamingHubMethod<{implTypeName}, {requestType}>(\"{serviceName}\", \"{method.MethodName}\", {invokerLambda}),");
        }
        else
        {
            // MagicOnionStreamingHubMethod<TService, TRequest, TResponse>
            sb.AppendLine($"{indent}new global::MagicOnion.Server.Binder.MagicOnionStreamingHubMethod<{implTypeName}, {requestType}, {responseType}>(\"{serviceName}\", \"{method.MethodName}\", {invokerLambda}),");
        }
    }

    static string GenerateHubInvokerLambda(ServiceImplementationInfo service, StreamingHubMethodInfo method)
    {
        var implTypeName = service.ImplementationType.FullName;
        var requestType = method.RequestType.FullName;

        if (method.Parameters.Count == 0)
        {
            return $"static ({implTypeName} instance, global::MagicOnion.Server.Hubs.StreamingHubContext context, {requestType} request) => instance.{method.MethodName}()";
        }
        else if (method.Parameters.Count == 1)
        {
            return $"static ({implTypeName} instance, global::MagicOnion.Server.Hubs.StreamingHubContext context, {requestType} request) => instance.{method.MethodName}(request)";
        }
        else
        {
            var args = string.Join(", ", method.Parameters.Select((p, i) => $"request.Item{i + 1}"));
            return $"static ({implTypeName} instance, global::MagicOnion.Server.Hubs.StreamingHubContext context, {requestType} request) => instance.{method.MethodName}({args})";
        }
    }

    static string GetSafeTypeName(MagicOnionTypeInfo typeInfo)
    {
        // Convert full type name to a safe identifier
        return typeInfo.FullName
            .Replace("global::", "")
            .Replace(".", "_")
            .Replace("<", "_")
            .Replace(">", "_")
            .Replace(",", "_")
            .Replace(" ", "");
    }
}
