using MagicOnion;
using MagicOnion.Server;
using MagicOnion.Server.Binder;
using MagicOnion.Server.Hubs;
using Xunit;

namespace MagicOnion.Server.SourceGenerator.Tests;

// Test service interface
public interface IGreeterService : IService<IGreeterService>
{
    UnaryResult<string> SayHello(string name);
    UnaryResult<int> Add(int a, int b);
    UnaryResult Ping();
}

// Test service implementation
public class GreeterService : ServiceBase<IGreeterService>, IGreeterService
{
    public UnaryResult<string> SayHello(string name)
    {
        return UnaryResult.FromResult($"Hello, {name}!");
    }

    public UnaryResult<int> Add(int a, int b)
    {
        return UnaryResult.FromResult(a + b);
    }

    public UnaryResult Ping()
    {
        return UnaryResult.CompletedResult;
    }
}

// Test hub interface
public interface IChatHubReceiver
{
    void OnMessage(string user, string message);
}

public interface IChatHub : IStreamingHub<IChatHub, IChatHubReceiver>
{
    Task JoinAsync(string roomName);
    Task<string> SendMessageAsync(string message);
    ValueTask LeaveAsync();
}

// Test hub implementation
public class ChatHub : StreamingHubBase<IChatHub, IChatHubReceiver>, IChatHub
{
    public Task JoinAsync(string roomName)
    {
        return Task.CompletedTask;
    }

    public Task<string> SendMessageAsync(string message)
    {
        return Task.FromResult($"Sent: {message}");
    }

    public ValueTask LeaveAsync()
    {
        return ValueTask.CompletedTask;
    }
}

// Generated method provider (this would be generated by the source generator)
[MagicOnionServerGeneration(typeof(GreeterService), typeof(ChatHub))]
public partial class TestMethodProvider
{
}

public class GeneratorTest
{
    [Fact]
    public void GeneratedProvider_ShouldImplementInterface()
    {
        // Arrange & Act
        var provider = new TestMethodProvider();

        // Assert
        Assert.IsAssignableFrom<IMagicOnionGrpcMethodProvider>(provider);
    }

    [Fact]
    public void GetGrpcMethods_ForService_ShouldReturnMethods()
    {
        // Arrange
        var provider = new TestMethodProvider();

        // Act
        var methods = provider.GetGrpcMethods<GreeterService>();

        // Assert
        Assert.NotEmpty(methods);
        Assert.Equal(3, methods.Count); // SayHello, Add, Ping
    }

    [Fact]
    public void GetGrpcMethods_ForHub_ShouldReturnConnectMethod()
    {
        // Arrange
        var provider = new TestMethodProvider();

        // Act
        var methods = provider.GetGrpcMethods<ChatHub>();

        // Assert
        Assert.Single(methods); // Connect method only
    }

    [Fact]
    public void GetStreamingHubMethods_ForHub_ShouldReturnHubMethods()
    {
        // Arrange
        var provider = new TestMethodProvider();

        // Act
        var methods = provider.GetStreamingHubMethods<ChatHub>();

        // Assert
        Assert.NotEmpty(methods);
        Assert.Equal(3, methods.Count); // JoinAsync, SendMessageAsync, LeaveAsync
    }

    [Fact]
    public void GetStreamingHubMethods_ForService_ShouldReturnEmpty()
    {
        // Arrange
        var provider = new TestMethodProvider();

        // Act
        var methods = provider.GetStreamingHubMethods<GreeterService>();

        // Assert
        Assert.Empty(methods);
    }
}
