// <auto-generated />
#pragma warning disable

namespace TempProject
{
    partial class MagicOnionInitializer
    {
        static partial class MagicOnionGeneratedClient
        {
            [global::MagicOnion.Ignore]
            public class TempProject_MyHubClient : global::MagicOnion.Client.StreamingHubClientBase<global::TempProject.IMyHub, global::TempProject.IMyHubReceiver>, global::TempProject.IMyHub
            {
                readonly global::MagicOnion.Client.IStreamingHubDiagnosticHandler diagnosticHandler;

                public TempProject_MyHubClient(global::TempProject.IMyHubReceiver receiver, global::Grpc.Core.CallInvoker callInvoker, global::MagicOnion.Client.StreamingHubClientOptions options, global::MagicOnion.Client.IStreamingHubDiagnosticHandler diagnosticHandler)
                    : base("IMyHub", receiver, callInvoker, options)
                {
                    this.diagnosticHandler = diagnosticHandler;
                }

                global::System.Threading.Tasks.Task<TResponse> WriteMessageWithResponseDiagnosticTaskAsync<TRequest, TResponse>(int methodId, TRequest message, [global::System.Runtime.CompilerServices.CallerMemberName] string callerMemberName = default!)
                {
                    if (diagnosticHandler is null)
                    {
                        return base.WriteMessageWithResponseTaskAsync<TRequest, TResponse>(methodId, message);
                    }

                    return diagnosticHandler.OnMethodInvoke(this, methodId, callerMemberName, message, isFireAndForget: true, base.WriteMessageWithResponseValueTaskOfTAsync<TRequest, TResponse>).AsTask();
                }

                async global::System.Threading.Tasks.ValueTask WriteMessageWithResponseDiagnosticValueTaskAsync<TRequest, TResponse>(int methodId, TRequest message, [global::System.Runtime.CompilerServices.CallerMemberName] string callerMemberName = default!)
                {
                    if (diagnosticHandler is null)
                    {
                        await base.WriteMessageWithResponseValueTaskAsync<TRequest, TResponse>(methodId, message);
                        return;
                    }

                    await diagnosticHandler.OnMethodInvoke(this, methodId, callerMemberName, message, isFireAndForget: true, base.WriteMessageWithResponseValueTaskOfTAsync<TRequest, TResponse>);
                }

                global::System.Threading.Tasks.ValueTask<TResponse> WriteMessageWithResponseDiagnosticValueTaskOfTAsync<TRequest, TResponse>(int methodId, TRequest message, [global::System.Runtime.CompilerServices.CallerMemberName] string callerMemberName = default!)
                {
                    if (diagnosticHandler is null)
                    {
                        return base.WriteMessageWithResponseValueTaskOfTAsync<TRequest, TResponse>(methodId, message);
                    }

                    return diagnosticHandler.OnMethodInvoke(this, methodId, callerMemberName, message, isFireAndForget: true, base.WriteMessageWithResponseValueTaskOfTAsync<TRequest, TResponse>);
                }

                global::System.Threading.Tasks.Task<TResponse> WriteMessageFireAndForgetDiagnosticTaskAsync<TRequest, TResponse>(int methodId, TRequest message, bool allowUnreliable = false, [global::System.Runtime.CompilerServices.CallerMemberName] string callerMemberName = default!)
                {
                    if (diagnosticHandler is null)
                    {
                        return base.WriteMessageFireAndForgetTaskAsync<TRequest, TResponse>(methodId, message, allowUnreliable);
                    }

                    return diagnosticHandler.OnMethodInvoke(this, methodId, callerMemberName, message, isFireAndForget: true, base.WriteMessageFireAndForgetValueTaskOfTAsync<TRequest, TResponse>).AsTask();
                }

                async global::System.Threading.Tasks.ValueTask WriteMessageFireAndForgetDiagnosticValueTaskAsync<TRequest, TResponse>(int methodId, TRequest message, bool allowUnreliable = false, [global::System.Runtime.CompilerServices.CallerMemberName] string callerMemberName = default!)
                {
                    if (diagnosticHandler is null)
                    {
                        await base.WriteMessageFireAndForgetTaskAsync<TRequest, TResponse>(methodId, message, allowUnreliable);
                        return;
                    }

                    await diagnosticHandler.OnMethodInvoke(this, methodId, callerMemberName, message, isFireAndForget: true, base.WriteMessageFireAndForgetValueTaskOfTAsync<TRequest, TResponse>);
                }

                global::System.Threading.Tasks.ValueTask<TResponse> WriteMessageFireAndForgetDiagnosticValueTaskOfTAsync<TRequest, TResponse>(int methodId, TRequest message, bool allowUnreliable = false, [global::System.Runtime.CompilerServices.CallerMemberName] string callerMemberName = default!)
                {
                    if (diagnosticHandler is null)
                    {
                        return base.WriteMessageFireAndForgetValueTaskOfTAsync<TRequest, TResponse>(methodId, message, allowUnreliable);
                    }

                    return diagnosticHandler.OnMethodInvoke(this, methodId, callerMemberName, message, isFireAndForget: true, base.WriteMessageFireAndForgetValueTaskOfTAsync<TRequest, TResponse>);
                }

                public global::System.Threading.Tasks.Task MethodA()
                    => this.WriteMessageWithResponseDiagnosticTaskAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1497325507, global::MessagePack.Nil.Default);
                public global::System.Threading.Tasks.Task<global::System.Int32> MethodB()
                    => this.WriteMessageWithResponseDiagnosticTaskAsync<global::MessagePack.Nil, global::System.Int32>(1514103126, global::MessagePack.Nil.Default);
                public global::System.Threading.Tasks.ValueTask MethodC()
                    => this.WriteMessageWithResponseDiagnosticValueTaskAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1530880745, global::MessagePack.Nil.Default);
                public global::System.Threading.Tasks.ValueTask<global::System.Int32> MethodD()
                    => this.WriteMessageWithResponseDiagnosticValueTaskOfTAsync<global::MessagePack.Nil, global::System.Int32>(1547658364, global::MessagePack.Nil.Default);
                public global::System.Threading.Tasks.Task MethodE(global::System.Int32 arg0, global::System.String arg1)
                    => this.WriteMessageWithResponseDiagnosticTaskAsync<global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String>, global::MessagePack.Nil>(1564435983, new global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String>(arg0, arg1));
                public global::System.Threading.Tasks.Task<global::System.String> MethodF(global::System.Int32 arg0, global::System.String arg1, global::System.Boolean arg2)
                    => this.WriteMessageWithResponseDiagnosticTaskAsync<global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String, global::System.Boolean>, global::System.String>(1581213602, new global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String, global::System.Boolean>(arg0, arg1, arg2));

                public global::TempProject.IMyHub FireAndForget()
                    => new FireAndForgetClient(this);

                [global::MagicOnion.Ignore]
                class FireAndForgetClient : global::TempProject.IMyHub
                {
                    readonly TempProject_MyHubClient parent;

                    public FireAndForgetClient(TempProject_MyHubClient parent)
                        => this.parent = parent;

                    public global::TempProject.IMyHub FireAndForget() => this;
                    public global::System.Threading.Tasks.Task DisposeAsync() => throw new global::System.NotSupportedException();
                    public global::System.Threading.Tasks.Task WaitForDisconnect() => throw new global::System.NotSupportedException();

                    public global::System.Threading.Tasks.Task MethodA()
                        => parent.WriteMessageFireAndForgetDiagnosticTaskAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1497325507, global::MessagePack.Nil.Default);
                    public global::System.Threading.Tasks.Task<global::System.Int32> MethodB()
                        => parent.WriteMessageFireAndForgetDiagnosticTaskAsync<global::MessagePack.Nil, global::System.Int32>(1514103126, global::MessagePack.Nil.Default);
                    public global::System.Threading.Tasks.ValueTask MethodC()
                        => parent.WriteMessageFireAndForgetDiagnosticValueTaskAsync<global::MessagePack.Nil, global::MessagePack.Nil>(1530880745, global::MessagePack.Nil.Default);
                    public global::System.Threading.Tasks.ValueTask<global::System.Int32> MethodD()
                        => parent.WriteMessageFireAndForgetDiagnosticValueTaskOfTAsync<global::MessagePack.Nil, global::System.Int32>(1547658364, global::MessagePack.Nil.Default);
                    public global::System.Threading.Tasks.Task MethodE(global::System.Int32 arg0, global::System.String arg1)
                        => parent.WriteMessageFireAndForgetDiagnosticTaskAsync<global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String>, global::MessagePack.Nil>(1564435983, new global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String>(arg0, arg1));
                    public global::System.Threading.Tasks.Task<global::System.String> MethodF(global::System.Int32 arg0, global::System.String arg1, global::System.Boolean arg2)
                        => parent.WriteMessageFireAndForgetDiagnosticTaskAsync<global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String, global::System.Boolean>, global::System.String>(1581213602, new global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String, global::System.Boolean>(arg0, arg1, arg2));

                }

                protected override void OnBroadcastEvent(global::System.Int32 methodId, global::System.ReadOnlyMemory<global::System.Byte> data)
                {
                    diagnosticHandler?.OnBroadcastEventRaw(this, methodId, data);
                    switch (methodId)
                    {
                        case -1005848884: // Void A()
                            {
                                var value = base.Deserialize<global::MessagePack.Nil>(data);
                                diagnosticHandler?.OnBroadcastEvent(this, "A", value);
                                receiver.A();
                            }
                            break;
                        case -955516027: // Void B(global::System.Int32 arg0, global::System.String arg1, global::System.Boolean arg2)
                            {
                                var value = base.Deserialize<global::MagicOnion.DynamicArgumentTuple<global::System.Int32, global::System.String, global::System.Boolean>>(data);
                                diagnosticHandler?.OnBroadcastEvent(this, "B", value);
                                receiver.B(value.Item1, value.Item2, value.Item3);
                            }
                            break;
                    }
                }

                protected override void OnResponseEvent(global::System.Int32 methodId, global::System.Object taskSource, global::System.ReadOnlyMemory<global::System.Byte> data)
                {
                    switch (methodId)
                    {
                        case 1497325507: // Task MethodA()
                            diagnosticHandler?.OnResponseEvent<TempProject_MyHubClient, global::MessagePack.Nil>(this, "MethodA", data);
                            base.SetResultForResponse<global::MessagePack.Nil>(taskSource, data);
                            break;
                        case 1514103126: // Task<Int32> MethodB()
                            diagnosticHandler?.OnResponseEvent<TempProject_MyHubClient, global::System.Int32>(this, "MethodB", data);
                            base.SetResultForResponse<global::System.Int32>(taskSource, data);
                            break;
                        case 1530880745: // ValueTask MethodC()
                            diagnosticHandler?.OnResponseEvent<TempProject_MyHubClient, global::MessagePack.Nil>(this, "MethodC", data);
                            base.SetResultForResponse<global::MessagePack.Nil>(taskSource, data);
                            break;
                        case 1547658364: // ValueTask<Int32> MethodD()
                            diagnosticHandler?.OnResponseEvent<TempProject_MyHubClient, global::System.Int32>(this, "MethodD", data);
                            base.SetResultForResponse<global::System.Int32>(taskSource, data);
                            break;
                        case 1564435983: // Task MethodE(global::System.Int32 arg0, global::System.String arg1)
                            diagnosticHandler?.OnResponseEvent<TempProject_MyHubClient, global::MessagePack.Nil>(this, "MethodE", data);
                            base.SetResultForResponse<global::MessagePack.Nil>(taskSource, data);
                            break;
                        case 1581213602: // Task<String> MethodF(global::System.Int32 arg0, global::System.String arg1, global::System.Boolean arg2)
                            diagnosticHandler?.OnResponseEvent<TempProject_MyHubClient, global::System.String>(this, "MethodF", data);
                            base.SetResultForResponse<global::System.String>(taskSource, data);
                            break;
                    }
                }

                protected override void OnClientResultEvent(global::System.Int32 methodId, global::System.Guid messageId, global::System.ReadOnlyMemory<global::System.Byte> data)
                {
                }
            }
        }
    }
}
