using MagicOnion.Server;
using MagicOnion.Server.Binder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

// ReSharper disable once CheckNamespace
namespace Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Extension methods for configuring MagicOnion server.
/// </summary>
public static class MagicOnionServerBuilderExtensions
{
    /// <summary>
    /// Uses a static method provider for AOT-compatible service registration.
    /// This replaces the default dynamic method provider with a source-generated one.
    /// </summary>
    /// <typeparam name="TProvider">The type of the static method provider generated by MagicOnion.Server.SourceGenerator.</typeparam>
    /// <param name="builder">The MagicOnion server builder.</param>
    /// <returns>The MagicOnion server builder for chaining.</returns>
    /// <remarks>
    /// Use this method when publishing with Native AOT or when you want to avoid reflection-based service discovery.
    /// The provider type should be a partial class decorated with [MagicOnionServerGeneration] attribute.
    /// </remarks>
    /// <example>
    /// <code>
    /// // In your Program.cs
    /// builder.Services.AddMagicOnion()
    ///     .UseStaticMethodProvider&lt;MagicOnionGeneratedMethodProvider&gt;();
    /// 
    /// // In a separate file
    /// [MagicOnionServerGeneration]
    /// public partial class MagicOnionGeneratedMethodProvider { }
    /// </code>
    /// </example>
    public static IMagicOnionServerBuilder UseStaticMethodProvider<TProvider>(this IMagicOnionServerBuilder builder)
        where TProvider : class, IMagicOnionGrpcMethodProvider, new()
    {
        // Remove the default dynamic provider and replace with the static one
        builder.Services.RemoveAll<IMagicOnionGrpcMethodProvider>();
        builder.Services.AddSingleton<IMagicOnionGrpcMethodProvider>(new TProvider());

        return builder;
    }

    /// <summary>
    /// Uses a static method provider instance for AOT-compatible service registration.
    /// </summary>
    /// <param name="builder">The MagicOnion server builder.</param>
    /// <param name="provider">The static method provider instance.</param>
    /// <returns>The MagicOnion server builder for chaining.</returns>
    public static IMagicOnionServerBuilder UseStaticMethodProvider(this IMagicOnionServerBuilder builder, IMagicOnionGrpcMethodProvider provider)
    {
        if (provider is null) throw new ArgumentNullException(nameof(provider));

        // Remove the default dynamic provider and replace with the static one
        builder.Services.RemoveAll<IMagicOnionGrpcMethodProvider>();
        builder.Services.AddSingleton(provider);

        return builder;
    }
}
