using MagicOnion.Server;
using MagicOnion.Server.Binder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;

// ReSharper disable once CheckNamespace
namespace Microsoft.Extensions.DependencyInjection;

/// <summary>
/// Extension methods for configuring MagicOnion server.
/// </summary>
public static class MagicOnionServerBuilderExtensions
{
    /// <summary>
    /// Uses a static method provider for AOT-compatible service registration.
    /// This replaces the default dynamic method provider with a source-generated one.
    /// </summary>
    /// <typeparam name="TProvider">The type of the static method provider generated by MagicOnion.Server.SourceGenerator.</typeparam>
    /// <param name="builder">The MagicOnion server builder.</param>
    /// <returns>The MagicOnion server builder for chaining.</returns>
    /// <remarks>
    /// Use this method when publishing with Native AOT or when you want to avoid reflection-based service discovery.
    /// The provider type should be a partial class decorated with [MagicOnionServerGeneration] attribute.
    /// </remarks>
    /// <example>
    /// <code>
    /// // In your Program.cs
    /// builder.Services.AddMagicOnion()
    ///     .UseStaticMethodProvider&lt;MagicOnionGeneratedMethodProvider&gt;();
    /// 
    /// // In a separate file
    /// [MagicOnionServerGeneration]
    /// public partial class MagicOnionGeneratedMethodProvider { }
    /// </code>
    /// </example>
    public static IMagicOnionServerBuilder UseStaticMethodProvider<TProvider>(this IMagicOnionServerBuilder builder)
        where TProvider : class, IMagicOnionGrpcMethodProvider, new()
    {
        // Remove the default dynamic provider and replace with the static one
        builder.Services.RemoveAll<IMagicOnionGrpcMethodProvider>();
        builder.Services.AddSingleton<IMagicOnionGrpcMethodProvider>(new TProvider());

        return builder;
    }

    /// <summary>
    /// Uses a static method provider instance for AOT-compatible service registration.
    /// </summary>
    /// <param name="builder">The MagicOnion server builder.</param>
    /// <param name="provider">The static method provider instance.</param>
    /// <returns>The MagicOnion server builder for chaining.</returns>
    public static IMagicOnionServerBuilder UseStaticMethodProvider(this IMagicOnionServerBuilder builder, IMagicOnionGrpcMethodProvider provider)
    {
        if (provider is null) throw new ArgumentNullException(nameof(provider));

        // Remove the default dynamic provider and replace with the static one
        builder.Services.RemoveAll<IMagicOnionGrpcMethodProvider>();
        builder.Services.AddSingleton(provider);

        return builder;
    }

    /// <summary>
    /// Uses a static Multicaster proxy factory for AOT-compatible StreamingHub broadcast.
    /// This replaces the default dynamic proxy factories with a source-generated one.
    /// </summary>
    /// <typeparam name="TProxyFactory">The type of the static proxy factory generated by Multicaster.SourceGenerator.</typeparam>
    /// <param name="builder">The MagicOnion server builder.</param>
    /// <returns>The MagicOnion server builder for chaining.</returns>
    /// <remarks>
    /// Use this method when publishing with Native AOT to enable StreamingHub broadcast features.
    /// The factory type should be a partial class decorated with [MulticasterProxyGeneration] attribute
    /// that lists all your StreamingHub receiver interfaces.
    /// </remarks>
    /// <example>
    /// <code>
    /// // In your Program.cs
    /// builder.Services.AddMagicOnion()
    ///     .UseStaticMethodProvider&lt;MagicOnionGeneratedMethodProvider&gt;()
    ///     .UseStaticProxyFactory&lt;MulticasterGeneratedProxyFactory&gt;();
    /// 
    /// // In a separate file
    /// [MulticasterProxyGeneration(typeof(IChatHubReceiver), typeof(IGameHubReceiver))]
    /// public partial class MulticasterGeneratedProxyFactory { }
    /// </code>
    /// </example>
    public static IMagicOnionServerBuilder UseStaticProxyFactory<TProxyFactory>(this IMagicOnionServerBuilder builder)
        where TProxyFactory : class, Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory, Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory, new()
    {
        var factory = new TProxyFactory();

        // Remove the default dynamic factories and replace with the static one
        builder.Services.RemoveAll<Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory>();
        builder.Services.RemoveAll<Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory>();

        builder.Services.AddSingleton<Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory>(factory);
        builder.Services.AddSingleton<Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory>(factory);

        return builder;
    }

    /// <summary>
    /// Uses a static Multicaster proxy factory instance for AOT-compatible StreamingHub broadcast.
    /// </summary>
    /// <typeparam name="TProxyFactory">The type of the proxy factory that implements both IInMemoryProxyFactory and IRemoteProxyFactory.</typeparam>
    /// <param name="builder">The MagicOnion server builder.</param>
    /// <param name="factory">The static proxy factory instance.</param>
    /// <returns>The MagicOnion server builder for chaining.</returns>
    public static IMagicOnionServerBuilder UseStaticProxyFactory<TProxyFactory>(this IMagicOnionServerBuilder builder, TProxyFactory factory)
        where TProxyFactory : class, Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory, Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory
    {
        if (factory is null) throw new ArgumentNullException(nameof(factory));

        // Remove the default dynamic factories and replace with the static one
        builder.Services.RemoveAll<Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory>();
        builder.Services.RemoveAll<Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory>();

        builder.Services.AddSingleton<Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory>(factory);
        builder.Services.AddSingleton<Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory>(factory);

        return builder;
    }

    /// <summary>
    /// Configures MagicOnion for AOT-only mode by disabling dynamic Multicaster proxies.
    /// Use this when you don't need StreamingHub broadcast features or when targeting Native AOT.
    /// </summary>
    /// <param name="builder">The MagicOnion server builder.</param>
    /// <returns>The MagicOnion server builder for chaining.</returns>
    /// <remarks>
    /// This method removes the dynamic proxy factories that are incompatible with AOT.
    /// StreamingHub broadcast features (like BroadcastToAll) will not work when this is enabled.
    /// </remarks>
    public static IMagicOnionServerBuilder DisableDynamicMulticaster(this IMagicOnionServerBuilder builder)
    {
        // Remove dynamic Multicaster factories that use System.Reflection.Emit
        builder.Services.RemoveAll<Cysharp.Runtime.Multicast.InMemory.IInMemoryProxyFactory>();
        builder.Services.RemoveAll<Cysharp.Runtime.Multicast.Remoting.IRemoteProxyFactory>();

        return builder;
    }
}
