// <auto-generated />
#pragma warning disable

namespace MyApplication1
{
    using global::System;
    using global::MemoryPack;
    partial class MagicOnionInitializer
    {
        /// <summary>
        /// Registers the generated MemoryPackFormatters.
        /// </summary>
        public static void RegisterMemoryPackFormatters()
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MagicOnion.Serialization.MemoryPack.DynamicArgumentTupleFormatter<global::System.String, global::System.Int32>());
        }
    }
}
