// <auto-generated />
#pragma warning disable CS0618 // 'member' is obsolete: 'text'
#pragma warning disable CS0612 // 'member' is obsolete

namespace MagicOnion
{
    using global::System;
    using global::MemoryPack;
    public class MagicOnionMemoryPackFormatterProvider
    {
        public static void RegisterFormatters()
        {
            global::MemoryPack.MemoryPackFormatterProvider.Register(new global::MagicOnion.Serialization.MemoryPack.DynamicArgumentTupleFormatter<global::System.String, global::System.Int32>());
        }
    }
}
