import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    //{type: 'autogenerated', dirName: '.'},
    'index',
    'features',
    'supported-platforms',
    'quickstart',
    {
      type: 'category',
      label: 'Installation',
      items: [
        'installation/index',
        'installation/unity'
      ],
    },
    {
      type: 'category',
      label: 'What\'s new',
      collapsed: true,
      items: [
        'release-notes/7.0',
      ],
    },
    {
      type: 'category',
      label: 'Fundamentals',
      items: [
        'fundamentals/unary-or-streaminghub',
        'fundamentals/exceptions-and-status-codes',
        'fundamentals/lifecycle',
        'fundamentals/aot',
      ],
    },
    {
      type: 'category',
      label: 'Unary service',
      items: [
        'unary/index',
        'unary/raw-bytes-response',
      ],
    },
    {
      type: 'category',
      label: 'StreamingHub service',
      items: [
        'streaminghub/index',
        'streaminghub/getting-started',
        'streaminghub/define-interface',
        {
          type: 'category',
          label: 'Group',
          items:[
            'streaminghub/group',
            'streaminghub/group-application-managed',
            'streaminghub/group-backplane',
          ]
        },
        'streaminghub/processing-order',
        'streaminghub/server-events',
        'streaminghub/disconnection',
        'streaminghub/heartbeat',
        'streaminghub/client-results',
      ],
    },
    {
      type: 'category',
      label: 'Filter',
      items:[
        'filter/index',
        'filter/client-filter',
        'filter/extensibility',
        'filter/di',
      ]
    },
    {
      type: 'category',
      label: 'Integration',
      items: [
        'integration/unity',
        'integration/di',
        'integration/json-transcoding',
        'integration/metrics',
      ]
    },
    {
      type: 'category',
      label: 'Source Generator',
      items: [
        'source-generator/client',
      ]
    },
    {
      type: 'category',
      label: 'Advanced',
      items: [
        'advanced/customize-serialization-encryption',
        'advanced/magiconionoptions',
        'advanced/map-service-endpoints',
        'advanced/version-compatibility',
        'advanced/memorypack',
        'advanced/raw-grpc'
      ]
    }
  ],
};

export default sidebars;
