// <auto-generated />
#pragma warning disable CS0618 // 'member' is obsolete: 'text'
#pragma warning disable CS0612 // 'member' is obsolete

namespace MagicOnion.Formatters
{
    using global::System;
    using global::MessagePack;

    public sealed class MyClass_MyEnumFormatter : global::MessagePack.Formatters.IMessagePackFormatter<global::TempProject.MyClass.MyEnum>
    {
        public void Serialize(ref global::MessagePack.MessagePackWriter writer, global::TempProject.MyClass.MyEnum value, global::MessagePack.MessagePackSerializerOptions options)
        {
            writer.Write((Int32)value);
        }
        
        public global::TempProject.MyClass.MyEnum Deserialize(ref global::MessagePack.MessagePackReader reader, global::MessagePack.MessagePackSerializerOptions options)
        {
            return (global::TempProject.MyClass.MyEnum)reader.ReadInt32();
        }
    }
}
