name: "(Legacy) Update pre-built SourceGenerator for Unity"

on:
  workflow_dispatch:

jobs:
  update-sourcegenerator-unity:
    name: Update MagicOnion.Client.SourceGenerator.Unity
    permissions:
      contents: read
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - run: echo "Not supported in v7 or later." && exit 1
